### ISSUE TITLE
Use TaskStatus::Reason to automatically retry jobs that fail because of Docker.

### ISSUE THREAD

**Issue by Rob-Johnson** [Yelp/chronos#57]
It's not rare in Yelp's environment to have sporadic docker issues that prevents the executor from launching a container. Users are often confused as to why their jobs failed, because we don't really expose the 'why' of a failure unless it was caused by the job - docker failures, in particular, don't show up in sandbox logs. Users don't really care about Docker, and this kind of failure is not the same as a regular application failure, so we shouldn't hold it to the same behaviour as specified by the ``retries`` key. We should *always* retry if this was just a random docker thing.

**Comment by Rob-Johnson** [comment]
Experimenting, I've found that we can definitely work with this. We even get a reason! @sjaensch I don't yet know how I can expose this to paasta but I can atleast do some logic to try again if the executor failed. @solarkennedy got any thoughts on **where** I can show this message? We don't expose per-task stuff from Chronos.


```
INFO Task with id 'ct:1485442840000:0:parentjob:' failed. Reason: REASON_COMMAND_EXECUTOR_FAILED Slave: 334 Message: Failed to launch container: Failed to run 'docker -H unix:///var/run/docker.sock pull foo:latest': exited with status 1; stderr='Error: image library/foo:latest not found
' (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:234)
````

**Comment by Rob-Johnson** [comment]
marathon exposes this stuff through it's event bus, btw

**Comment by solarkennedy** [comment]
close wontfix?
